-- Adatbázis létrehozása

IF NOT Exists (SELECT * FROM sys.databases WHERE name = 'MyFleet')
BEGIN

/****** Object:  Database [MyFleet]    Script Date: 2022. 06. 20. 8:50:44 ******/
CREATE DATABASE [MyFleet]

ALTER DATABASE [MyFleet] SET ANSI_NULL_DEFAULT OFF 

ALTER DATABASE [MyFleet] SET ANSI_NULLS OFF 

ALTER DATABASE [MyFleet] SET ANSI_PADDING OFF 

ALTER DATABASE [MyFleet] SET ANSI_WARNINGS OFF 

ALTER DATABASE [MyFleet] SET ARITHABORT OFF 

ALTER DATABASE [MyFleet] SET AUTO_CLOSE OFF 

ALTER DATABASE [MyFleet] SET AUTO_SHRINK OFF 

ALTER DATABASE [MyFleet] SET AUTO_UPDATE_STATISTICS ON 

ALTER DATABASE [MyFleet] SET CURSOR_CLOSE_ON_COMMIT OFF 

ALTER DATABASE [MyFleet] SET CURSOR_DEFAULT  GLOBAL 

ALTER DATABASE [MyFleet] SET CONCAT_NULL_YIELDS_NULL OFF 

ALTER DATABASE [MyFleet] SET NUMERIC_ROUNDABORT OFF 

ALTER DATABASE [MyFleet] SET QUOTED_IDENTIFIER OFF 

ALTER DATABASE [MyFleet] SET RECURSIVE_TRIGGERS OFF 

ALTER DATABASE [MyFleet] SET  DISABLE_BROKER 

ALTER DATABASE [MyFleet] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 

ALTER DATABASE [MyFleet] SET DATE_CORRELATION_OPTIMIZATION OFF 

ALTER DATABASE [MyFleet] SET TRUSTWORTHY OFF 

ALTER DATABASE [MyFleet] SET ALLOW_SNAPSHOT_ISOLATION OFF 

ALTER DATABASE [MyFleet] SET PARAMETERIZATION SIMPLE 

ALTER DATABASE [MyFleet] SET READ_COMMITTED_SNAPSHOT OFF 

ALTER DATABASE [MyFleet] SET HONOR_BROKER_PRIORITY OFF 

ALTER DATABASE [MyFleet] SET RECOVERY FULL 

ALTER DATABASE [MyFleet] SET  MULTI_USER 

ALTER DATABASE [MyFleet] SET PAGE_VERIFY CHECKSUM  

ALTER DATABASE [MyFleet] SET DB_CHAINING OFF 

ALTER DATABASE [MyFleet] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 

ALTER DATABASE [MyFleet] SET TARGET_RECOVERY_TIME = 60 SECONDS 

ALTER DATABASE [MyFleet] SET DELAYED_DURABILITY = DISABLED 

ALTER DATABASE [MyFleet] SET ACCELERATED_DATABASE_RECOVERY = OFF  

ALTER DATABASE [MyFleet] SET QUERY_STORE = OFF

ALTER DATABASE [MyFleet] SET  READ_WRITE

END